// Mechanically extracted from the fixed upstream snapshot.
export const shaders = {
  "vertShader": "precision highp float;\n\n    varying vec2 vUv;\n    attribute vec2 a_position;\n\n    varying vec2 vL;\n    varying vec2 vR;\n    varying vec2 vT;\n    varying vec2 vB;\n    uniform vec2 u_texel;\n\n    void main () {\n        vUv = .5 * (a_position + 1.);\n        vL = vUv - vec2(u_texel.x, 0.);\n        vR = vUv + vec2(u_texel.x, 0.);\n        vT = vUv + vec2(0., u_texel.y);\n        vB = vUv - vec2(0., u_texel.y);\n        gl_Position = vec4(a_position, 0., 1.);\n    }",
  "fragShaderAdvection": "precision highp float;\n    precision highp sampler2D;\n\n    varying vec2 vUv;\n    uniform sampler2D u_velocity_texture;\n    uniform sampler2D u_input_texture;\n    uniform vec2 u_texel;\n    uniform float u_dt;\n    uniform float u_use_text;\n    uniform sampler2D u_text_texture;\n\n    vec4 bilerp (sampler2D sam, vec2 uv, vec2 tsize) {\n        vec2 st = uv / tsize - 0.5;\n\n        vec2 iuv = floor(st);\n        vec2 fuv = fract(st);\n\n        vec4 a = texture2D(sam, (iuv + vec2(0.5, 0.5)) * tsize);\n        vec4 b = texture2D(sam, (iuv + vec2(1.5, 0.5)) * tsize);\n        vec4 c = texture2D(sam, (iuv + vec2(0.5, 1.5)) * tsize);\n        vec4 d = texture2D(sam, (iuv + vec2(1.5, 1.5)) * tsize);\n\n        return mix(mix(a, b, fuv.x), mix(c, d, fuv.x), fuv.y);\n    }\n\n    void main () {\n        vec2 coord = vUv - u_dt * bilerp(u_velocity_texture, vUv, u_texel).xy * u_texel;\n        float text = texture2D(u_text_texture, vec2(vUv.x, 1. - vUv.y)).r;\n        float dissipation = (.96 + text * .04 * u_use_text);\n\n        gl_FragColor = dissipation * bilerp(u_input_texture, coord, u_texel);\n        gl_FragColor.a = 1.;\n    }",
  "fragShaderDivergence": "precision highp float;\n    precision highp sampler2D;\n\n    varying highp vec2 vUv;\n    varying highp vec2 vL;\n    varying highp vec2 vR;\n    varying highp vec2 vT;\n    varying highp vec2 vB;\n    uniform sampler2D u_velocity_texture;\n\n    void main () {\n        float L = texture2D(u_velocity_texture, vL).x;\n        float R = texture2D(u_velocity_texture, vR).x;\n        float T = texture2D(u_velocity_texture, vT).y;\n        float B = texture2D(u_velocity_texture, vB).y;\n\n        float div = .6 * (R - L + T - B);\n        gl_FragColor = vec4(div, 0., 0., 1.);\n    }",
  "fragShaderPressure": "precision highp float;\n    precision highp sampler2D;\n\n    varying highp vec2 vUv;\n    varying highp vec2 vL;\n    varying highp vec2 vR;\n    varying highp vec2 vT;\n    varying highp vec2 vB;\n    uniform sampler2D u_pressure_texture;\n    uniform sampler2D u_divergence_texture;\n    uniform sampler2D u_text_texture;\n\n    void main () {\n\n        float text = texture2D(u_text_texture, vec2(vUv.x, 1. - vUv.y)).r;\n\n        float L = texture2D(u_pressure_texture, vL).x;\n        float R = texture2D(u_pressure_texture, vR).x;\n        float T = texture2D(u_pressure_texture, vT).x;\n        float B = texture2D(u_pressure_texture, vB).x;\n        float C = texture2D(u_pressure_texture, vUv).x;\n        float divergence = texture2D(u_divergence_texture, vUv).x;\n\n        float pressure = (L + R + B + T - divergence) * 0.25;\n        pressure += (.2 * text);\n\n        gl_FragColor = vec4(pressure, 0., 0., 1.);\n    }",
  "fragShaderGradientSubtract": "precision highp float;\n    precision highp sampler2D;\n\n    varying highp vec2 vUv;\n    varying highp vec2 vL;\n    varying highp vec2 vR;\n    varying highp vec2 vT;\n    varying highp vec2 vB;\n    uniform sampler2D u_pressure_texture;\n    uniform sampler2D u_velocity_texture;\n\n    uniform sampler2D u_text_texture;\n\n    void main () {\n        float L = texture2D(u_pressure_texture, vL).x;\n        float R = texture2D(u_pressure_texture, vR).x;\n        float T = texture2D(u_pressure_texture, vT).x;\n        float B = texture2D(u_pressure_texture, vB).x;\n        vec2 velocity = texture2D(u_velocity_texture, vUv).xy;\n        velocity.xy -= vec2(R - L, T - B);\n        gl_FragColor = vec4(velocity, 0., 1.);\n    }",
  "fragShaderPoint": "precision highp float;\n    precision highp sampler2D;\n\n    varying vec2 vUv;\n    uniform sampler2D u_input_texture;\n    uniform float u_ratio;\n    uniform vec3 u_point_value;\n    uniform vec2 u_point;\n    uniform float u_point_size;\n\n    uniform sampler2D u_text_texture;\n\n\n    void main () {\n        vec2 p = vUv - u_point.xy;\n        p.x *= u_ratio;\n        vec3 splat = pow(2., -dot(p, p) / u_point_size) * u_point_value;\n\n        float text = texture2D(u_text_texture, vec2(vUv.x, 1. - vUv.y)).r;\n        splat *= (.7 + .2 * text);\n\n        vec3 base = texture2D(u_input_texture, vUv).xyz;\n        gl_FragColor = vec4(base + splat, 1.);\n    }",
  "fragShaderOutputShader": "precision highp float;\n    precision highp sampler2D;\n\n    varying vec2 vUv;\n    uniform sampler2D u_output_texture;\n    uniform sampler2D u_text_texture;\n\n    void main () {\n        vec3 C = texture2D(u_output_texture, vUv).rgb;\n        float text = texture2D(u_text_texture, vec2(vUv.x, 1. - vUv.y)).r; \n        gl_FragColor = vec4(vec3(1.) - C, 1.);\n    }"
};
